### ISSUE TITLE
No new files are created

### ISSUE THREAD

**Issue by leicray** [sunray97/newfile-from-template#1]
I cannot get this extension to work. A menu is installed in Brackets, but selecting a menu item does not do anything at all. I'm running Release 1.1 experimental build 1.1.0-15558 (release ea908cae5) on Linux Mint and (presumably?) the same version on Windows 7. The extension works on neither platform.

Perhaps I'm missing something obvious, but there is little or no help provided with the extension.

Thanks.

**Comment by sunray97** [comment]
I updated a new version. you can try it again.

**Comment by leicray** [comment]
That seems to work now. Many thanks.
