### ISSUE TITLE
from current file as template

### ISSUE THREAD

**Issue by MortalCatalyst** [sunray97/newfile-from-template#4]
If I have a index.html which I have edited and now want to make 3 copies of for my about.html contact.html and info.html how do I use the current file as the template?

**Comment by sakshamsaxena** [comment]
To use a different file, I'd suggest changing the contents of existing template file in the extensions folder. 
As mentioned in readme, just don't change the file name of template.

**Comment by MortalCatalyst** [comment]
Thanks
