### ISSUE TITLE
Version 1.1.1 not available for install

### ISSUE THREAD

**Issue by sakshamsaxena** [sunray97/newfile-from-template#5]
Hey! 
Was just trying to reinstall the extension from Extension Manager. Saw this then:
![capture](https://cloud.githubusercontent.com/assets/8774516/5792021/23757bee-9f27-11e4-9f88-9b8d860c7803.PNG)

Went back to the code and saw that you wrote ">=1.1.1" in requirement of Brackets in the file "package.json"

That's a big screw up buddy! The updated version is not even available! 
Please fix and test also. I am 90% sure that the error is caused because brackets engine is written two times, but I can't say 100%. So I'm leaving it up to you :+1:

**Comment by sunray97** [comment]
Thanks bro!
